defaults:
  - /benchmark/prompt/evaluate@mt_bench.prompt_template: mt_bench_en_prompt_v0
  - /benchmark/prompt/evaluate@ja_mt_bench.prompt_template: mt_bench_ja_prompt_v1

ichikara:
  name: ichikara
  metric: abs_quality
  system_prompt: 以下は、タスクを説明する指示です。要求を適切に満たす応答を書きなさい。
  sampling_params:
    max_tokens: 1024
    seed: 1234
    top_p: 0.95
    temperature: 1.0
    frequency_penalty: 0.0
answer_carefully:
  name: answer_carefully
  use_reference: true
  metric: abs_safety
  system_prompt: 以下は、タスクを説明する指示です。要求を適切に満たす応答を書きなさい。
  api_error_score: 1 # API呼び出しがエラーになった場合のスコア(nullの場合はエラーを無視)
  sampling_params:
    max_tokens: 1024
    seed: 1234
    top_p: 0.95
    temperature: 1.0
    frequency_penalty: 0.0
mt_bench:
  name: mt_bench
  metric: mt_bench
  mode: single # Currently, only the 'single' mode is supported, and 'pairwise' mode is not supported.
  reference:
    path: ./src/llm_jp_gen_eval/data/mt_bench/reference_answer/gpt-4-v0.jsonl
    categories:
      - math
      - reasoning
      - coding
  sampling_params:
    max_tokens: 2048
    seed: null
    top_p: null
    temperature: 0
    frequency_penalty: null
ja_mt_bench:
  name: ja_mt_bench
  metric: mt_bench
  mode: single # Currently, only the 'single' mode is supported, and 'pairwise' mode is not supported.
  reference:
    path: ./src/llm_jp_gen_eval/data/ja_mt_bench/reference_answer/base-gpt4o-with-human-annotation-v0.jsonl
    categories:
      - math
      - reasoning
      - coding
  sampling_params:
    max_tokens: 2048
    seed: null
    top_p: null
    temperature: 0
    frequency_penalty: null