# Based on Stability-AI/FastChat (5d4f13a) (latest) : 'wandb-japan/llm-leaderboard/mtbench_ja_prompt:v1'
# https://github.com/wandb/llm-leaderboard/tree/g-leaderboard?tab=readme-ov-file#preparation-for-mtbench
single-math-v1:
  regex: \[\[(10|[1-9])\]\]
  prompt_template: |-
    [Instruction]
    Please act as an impartial judge and evaluate the quality of the response provided by an AI assistant to the user question displayed below. Your evaluation should consider correctness and helpfulness. You will be given a reference answer and the assistant's answer. Begin your evaluation by comparing the assistant's answer with the reference answer. Identify and correct any mistakes. Be as objective as possible. The expected language is Japanese. Responses in languages other than Japanese will incur score deductions unless specifically required. Failure to use Japanese at all will result in the lowest evaluation. However, using Japanese is not mandatory when providing only Python scripts or calculation results, where Japanese is not essential. Additionally, your explanation of judgement should be in Japanese. After providing your explanation, you must rate the response on a scale of 1 to 10 by strictly following this format: "[[rating]]", for example: "Rating: [[5]]".

    [Question]
    {question}

    [The Start of Reference Answer]
    {ref_answer_1}
    [The End of Reference Answer]

    [The Start of Assistant's Answer]
    {answer}
    [The End of Assistant's Answer]
  system_prompt: You are a helpful assistant.
single-math-v1-multi-turn:
  regex: \[\[(10|[1-9])\]\]
  prompt_template: |-
    <|The Start of Reference Answer|>

    ### User:
    {question_1}

    ### Reference answer:
    {ref_answer_1}

    ### User:
    {question_2}

    ### Reference answer:
    {ref_answer_2}

    <|The End of Reference Answer|>


    <|The Start of Assistant A's Conversation with User|>

    ### User:
    {question_1}

    ### Assistant A:
    {answer_1}

    ### User:
    {question_2}

    ### Assistant A:
    {answer_2}

    <|The End of Assistant A's Conversation with User|>
  system_prompt: |+
    Please act as an impartial judge and evaluate the quality of the response provided by an AI assistant to the user question. Your evaluation should consider correctness and helpfulness. You will be given a reference answer and the assistant's answer. You evaluation should focus on the assistant's answer to the second question. Begin your evaluation by comparing the assistant's answer with the reference answer. Identify and correct any mistakes. Be as objective as possible. The expected language is Japanese. Responses in languages other than Japanese will incur score deductions unless specifically required. Failure to use Japanese at all will result in the lowest evaluation. However, using Japanese is not mandatory when providing only Python scripts or calculation results, where Japanese is not essential. Additionally, your explanation of judgement should be in Japanese. After providing your explanation, you must rate the response on a scale of 1 to 10 by strictly following this format: "[[rating]]", for example: "Rating: [[5]]".
single-v1:
  regex: \[\[(10|[1-9])\]\]
  prompt_template: |-
    [Instruction]
    Please act as an impartial judge and evaluate the quality of the response provided by an AI assistant to the user question displayed below. Your evaluation should consider factors such as the helpfulness, relevance, accuracy, depth, creativity, and level of detail of the response. Begin your evaluation by providing a short explanation. Be as objective as possible. The expected language is Japanese. Responses in languages other than Japanese will incur score deductions unless specifically required. Failure to use Japanese at all will result in the lowest evaluation. However, using Japanese is not mandatory when providing only Python scripts or calculation results, where Japanese is not essential. Additionally, your explanation of judgement should be in Japanese. After providing your explanation, you must rate the response on a scale of 1 to 10 by strictly following this format: "[[rating]]", for example: "Rating: [[5]]".

    [Question]
    {question}

    [The Start of Assistant's Answer]
    {answer}
    [The End of Assistant's Answer]
  system_prompt: You are a helpful assistant.
  type: single
single-v1-multi-turn:
  regex: \[\[(10|[1-9])\]\]
  prompt_template: |-
    <|The Start of Assistant A's Conversation with User|>

    ### User:
    {question_1}

    ### Assistant A:
    {answer_1}

    ### User:
    {question_2}

    ### Assistant A:
    {answer_2}

    <|The End of Assistant A's Conversation with User|>
  system_prompt: |+
    Please act as an impartial judge and evaluate the quality of the response provided by an AI assistant to the user question displayed below. Your evaluation should consider factors such as the helpfulness, relevance, accuracy, depth, creativity, and level of detail of the response. You evaluation should focus on the assistant's answer to the second user question. Begin your evaluation by providing a short explanation. Be as objective as possible. The expected language is Japanese. Responses in languages other than Japanese will incur score deductions unless specifically required. Failure to use Japanese at all will result in the lowest evaluation. However, using Japanese is not mandatory when providing only Python scripts or calculation results, where Japanese is not essential. Additionally, your explanation of judgement should be in Japanese. After providing your explanation, you must rate the response on a scale of 1 to 10 by strictly following this format: "[[rating]]", for example: "Rating: [[5]]".