name: bedrock
model_name: anthropic.claude-3-5-sonnet-20240620-v1:0

max_retries: 1
async_request_interval: 10 # 非同期のリクエスト間隔(秒)
max_tokens: 4096
disable_system_prompt: false # システムプロンプトが無効になります。システムプロンプトが与えられた場合、ユーザープロンプトの先頭に結合されます。

